# Generated by Django 5.2.13 on 2026-04-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('bmi', models.FloatField()),
                ('goal', models.CharField(max_length=30)),
                ('activity_level', models.CharField(max_length=20)),
                ('experience_level', models.CharField(max_length=20)),
                ('workout', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('session_key', models.CharField(db_index=True, help_text='Browser session ID for tracking', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
